# Generated by Django 4.2.1 on 2023-09-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0004_alter_goalcategory_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardparticipant",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boardparticipant",
                to="goals.board",
                verbose_name="Board",
            ),
        ),
        migrations.AlterField(
            model_name="boardparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boardparticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="goalcategory",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="goals.board",
                verbose_name="Board",
            ),
        ),
    ]
