# Generated by Django 4.2.1 on 2023-09-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tguser",
            name="verification_code",
            field=models.PositiveBigIntegerField(
                null=True, verbose_name="Verification code"
            ),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="telegram_chat_id",
            field=models.PositiveIntegerField(verbose_name="Chat id"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="telegram_user_ud",
            field=models.PositiveIntegerField(verbose_name="Telegram user id"),
        ),
    ]
