# Generated by Django 4.2.1 on 2023-09-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0005_alter_boardparticipant_board_and_more"),
        ("bot", "0003_tguser_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tguser",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AddField(
            model_name="tguser",
            name="goal_creating_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Not initiated"),
                    (1, "Start"),
                    (2, "Chooding board"),
                    (3, "Choosing category"),
                    (4, "Choosing goal title"),
                ],
                default=0,
                null=True,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="telegram_chat_id",
            field=models.PositiveSmallIntegerField(verbose_name="Chat id"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="telegram_user_ud",
            field=models.PositiveSmallIntegerField(verbose_name="Telegram user id"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="verification_code",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Verification code"
            ),
        ),
        migrations.CreateModel(
            name="TgUserNewGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goals.board",
                        verbose_name="Board",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goals.goalcategory",
                        verbose_name="Goal Category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.tguser",
                        verbose_name="Tg User",
                    ),
                ),
            ],
        ),
    ]
