# Generated by Django 4.2.1 on 2023-09-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0006_alter_boardparticipant_board_and_more"),
        ("bot", "0005_rename_user_id_tguser_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TgUserNewGoal",
            new_name="TgUserGoal",
        ),
    ]
